<a href="https://colab.research.google.com/github/27priyanshu/Machine-Learning-Models/blob/main/Loan_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("/content/loan_data.csv")
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001003    Male     Yes          1      Graduate            No   
1    LP001005    Male     Yes          0      Graduate           Yes   
2    LP001006    Male     Yes          0  Not Graduate            No   
3    LP001008    Male      No          0      Graduate            No   
4    LP001013    Male     Yes          0  Not Graduate            No   
..        ...     ...     ...        ...           ...           ...   
376  LP002953    Male     Yes         3+      Graduate            No   
377  LP002974    Male     Yes          0      Graduate            No   
378  LP002978  Female      No          0      Graduate            No   
379  LP002979    Male     Yes         3+      Graduate            No   
380  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               4583             1508.0         128             360.0   
1               3000                0.0          66             360.0   
2               2583             2358.0         120             360.0   
3               6000                0.0         141             360.0   
4               2333             1516.0          95             360.0   
..               ...                ...         ...               ...   
376             5703                0.0         128             360.0   
377             3232             1950.0         108             360.0   
378             2900                0.0          71             360.0   
379             4106                0.0          40             180.0   
380             4583                0.0         133             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Rural           N  
1               1.0         Urban           Y  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
376             1.0         Urban           Y  
377             1.0         Rural           Y  
378             1.0         Rural           Y  
379             1.0         Rural           Y  
380             0.0     Semiurban           N  

[381 rows x 13 columns]

## EDA

In [3]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001003   Male     Yes          1      Graduate            No   
1  LP001005   Male     Yes          0      Graduate           Yes   
2  LP001006   Male     Yes          0  Not Graduate            No   
3  LP001008   Male      No          0      Graduate            No   
4  LP001013   Male     Yes          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             4583             1508.0         128             360.0   
1             3000                0.0          66             360.0   
2             2583             2358.0         120             360.0   
3             6000                0.0         141             360.0   
4             2333             1516.0          95             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Rural           N  
1             1.0         Urban           Y  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [5]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            381 non-null    object 
 1   Gender             376 non-null    object 
 2   Married            381 non-null    object 
 3   Dependents         373 non-null    object 
 4   Education          381 non-null    object 
 5   Self_Employed      360 non-null    object 
 6   ApplicantIncome    381 non-null    int64  
 7   CoapplicantIncome  381 non-null    float64
 8   LoanAmount         381 non-null    int64  
 9   Loan_Amount_Term   370 non-null    float64
 10  Credit_History     351 non-null    float64
 11  Property_Area      381 non-null    object 
 12  Loan_Status        381 non-null    object 
dtypes: float64(3), int64(2), object(8)
memory usage: 38.8+ KB


In [7]:
df.isnull().sum()

Loan_ID               0
Gender                5
Married               0
Dependents            8
Education             0
Self_Employed        21
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
df.drop(['Dependents','Loan_ID','Gender','Education','Self_Employed','Married'],axis=1,inplace=True)


In [9]:
df

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               4583             1508.0         128             360.0   
1               3000                0.0          66             360.0   
2               2583             2358.0         120             360.0   
3               6000                0.0         141             360.0   
4               2333             1516.0          95             360.0   
..               ...                ...         ...               ...   
376             5703                0.0         128             360.0   
377             3232             1950.0         108             360.0   
378             2900                0.0          71             360.0   
379             4106                0.0          40             180.0   
380             4583                0.0         133             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Rural           N  
1               1.0         Urban           Y  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
376             1.0         Urban           Y  
377             1.0         Rural           Y  
378             1.0         Rural           Y  
379             1.0         Rural           Y  
380             0.0     Semiurban           N  

[381 rows x 7 columns]

In [10]:
df.fillna(df['Loan_Amount_Term'].median(),axis=1,inplace=True)
df.fillna(df['Credit_History'].median(),axis=1,inplace=True)

In [11]:
df

ApplicantIncome CoapplicantIncome LoanAmount Loan_Amount_Term  \
0              4583            1508.0        128            360.0   
1              3000               0.0         66            360.0   
2              2583            2358.0        120            360.0   
3              6000               0.0        141            360.0   
4              2333            1516.0         95            360.0   
..              ...               ...        ...              ...   
376            5703               0.0        128            360.0   
377            3232            1950.0        108            360.0   
378            2900               0.0         71            360.0   
379            4106               0.0         40            180.0   
380            4583               0.0        133            360.0   

    Credit_History Property_Area Loan_Status  
0              1.0         Rural           N  
1              1.0         Urban           Y  
2              1.0         Urban           Y  
3              1.0         Urban           Y  
4              1.0         Urban           Y  
..             ...           ...         ...  
376            1.0         Urban           Y  
377            1.0         Rural           Y  
378            1.0         Rural           Y  
379            1.0         Rural           Y  
380            0.0     Semiurban           N  

[381 rows x 7 columns]

In [12]:
df.isnull().sum()


ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Property_Area'] = le.fit_transform(df['Property_Area'])
df['Loan_Status'] = le.fit_transform(df['Loan_Status'])


df

ApplicantIncome CoapplicantIncome LoanAmount Loan_Amount_Term  \
0              4583            1508.0        128            360.0   
1              3000               0.0         66            360.0   
2              2583            2358.0        120            360.0   
3              6000               0.0        141            360.0   
4              2333            1516.0         95            360.0   
..              ...               ...        ...              ...   
376            5703               0.0        128            360.0   
377            3232            1950.0        108            360.0   
378            2900               0.0         71            360.0   
379            4106               0.0         40            180.0   
380            4583               0.0        133            360.0   

    Credit_History  Property_Area  Loan_Status  
0              1.0              0            0  
1              1.0              2            1  
2              1.0              2            1  
3              1.0              2            1  
4              1.0              2            1  
..             ...            ...          ...  
376            1.0              2            1  
377            1.0              0            1  
378            1.0              0            1  
379            1.0              0            1  
380            0.0              1            0  

[381 rows x 7 columns]

In [14]:
y = np.array(df['Loan_Status'])

df.drop(['Loan_Status'],axis=1,inplace=True)

x = df.values

In [15]:
x


array([[4583, 1508.0, 128, 360.0, 1.0, 0],
       [3000, 0.0, 66, 360.0, 1.0, 2],
       [2583, 2358.0, 120, 360.0, 1.0, 2],
       ...,
       [2900, 0.0, 71, 360.0, 1.0, 0],
       [4106, 0.0, 40, 180.0, 1.0, 0],
       [4583, 0.0, 133, 360.0, 0.0, 1]], dtype=object)

In [16]:
y

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,

In [17]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(304, 6) (77, 6) (304,) (77,)


In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [19]:
lr = LinearRegression()

lr.fit(x_train,y_train)

lrp = lr.predict(x_test)

In [20]:
lrp=np.clip(np.round(lrp),0,1)
lrp


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
print(100-mean_absolute_error(y_test,lrp)*100)
print(100-mean_squared_error(y_test,lrp)*100)

71.42857142857143
71.42857142857143


In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score,confusion_matrix,classification_report,accuracy_score

In [23]:
lr = LogisticRegression()

lr.fit(x_train,y_train)

lrp = lr.predict(x_test)

In [24]:
lrp


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [25]:
print(r2_score(y_test,lrp)*100,'\n')
print(confusion_matrix(y_test,lrp),'\n')
print(classification_report(y_test,lrp),'\n')
print(100*accuracy_score(y_test,lrp),'\n')

-40.000000000000014 

[[ 0 22]
 [ 0 55]] 

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        22
           1       0.71      1.00      0.83        55

    accuracy                           0.71        77
   macro avg       0.36      0.50      0.42        77
weighted avg       0.51      0.71      0.60        77
 

71.42857142857143 

